# Generated by Django 3.2 on 2023-09-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_photo'),
        ('cart', '0002_auto_20230927_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='cart.CartItem', to='products.Product'),
        ),
    ]
