# Generated by Django 3.2 on 2023-09-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('FEM', 'Female'), ('MAL', 'Male')], max_length=10, verbose_name='Gender'),
        ),
    ]
