# Generated by Django 3.2 on 2023-09-14 02:02

import applications.products.utils.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to=applications.products.utils.models_utils.product_photo_file_path, verbose_name='Photo'),
        ),
    ]
